// src/main/webapp/app/entities/book/book/book-update.vue
<template>
    <div class="row justify-content-center">
        <div class="col-8">
            <form name="editForm" role="form" novalidate v-on:submit.prevent="save()" >
                <h2 id="gatewayApp.bookBook.home.createOrEditLabel" v-text="$t('gatewayApp.bookBook.home.createOrEditLabel')">Create or edit a Book</h2>
                <div>
                    <div class="form-group" v-if="book.id">
                        <label for="id" v-text="$t('global.field.id')">ID</label>
                        <input type="text" class="form-control" id="id" name="id"
                               v-model="book.id" readonly />
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('gatewayApp.bookBook.title')" for="book-title">Title</label>
                        <input type="text" class="form-control" name="title" id="book-title"
                            :class="{'valid': !$v.book.title.$invalid, 'invalid': $v.book.title.$invalid }" v-model="$v.book.title.$model" />
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('gatewayApp.bookBook.description')" for="book-description">Description</label>
                        <input type="text" class="form-control" name="description" id="book-description"
                            :class="{'valid': !$v.book.description.$invalid, 'invalid': $v.book.description.$invalid }" v-model="$v.book.description.$model" />
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('gatewayApp.bookBook.author')" for="book-author">Author</label>
                        <input type="text" class="form-control" name="author" id="book-author"
                            :class="{'valid': !$v.book.author.$invalid, 'invalid': $v.book.author.$invalid }" v-model="$v.book.author.$model" />
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('gatewayApp.bookBook.publisher')" for="book-publisher">Publisher</label>
                        <input type="text" class="form-control" name="publisher" id="book-publisher"
                            :class="{'valid': !$v.book.publisher.$invalid, 'invalid': $v.book.publisher.$invalid }" v-model="$v.book.publisher.$model" />
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('gatewayApp.bookBook.isbn')" for="book-isbn">Isbn</label>
                        <input type="number" class="form-control" name="isbn" id="book-isbn"
                            :class="{'valid': !$v.book.isbn.$invalid, 'invalid': $v.book.isbn.$invalid }" v-model.number="$v.book.isbn.$model" />
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('gatewayApp.bookBook.publicationDate')" for="book-publicationDate">Publication Date</label>
                        <b-input-group class="mb-3">
                            <b-input-group-prepend>
                                <b-form-datepicker
                                    aria-controls="book-publicationDate"
                                    v-model="$v.book.publicationDate.$model"
                                    name="publicationDate"
                                    class="form-control"
                                    :locale="currentLanguage"
                                    button-only
                                    today-button
                                    reset-button
                                    close-button
                                >
                                </b-form-datepicker>
                            </b-input-group-prepend>
                            <b-form-input id="book-publicationDate" type="text" class="form-control" name="publicationDate"  :class="{'valid': !$v.book.publicationDate.$invalid, 'invalid': $v.book.publicationDate.$invalid }"
                            v-model="$v.book.publicationDate.$model"  />
                        </b-input-group>
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('gatewayApp.bookBook.classification')" for="book-classification">Classification</label>
                        <select class="form-control" name="classification" :class="{'valid': !$v.book.classification.$invalid, 'invalid': $v.book.classification.$invalid }" v-model="$v.book.classification.$model" id="book-classification" >
                            <option value="Arts" v-bind:label="$t('gatewayApp.Classification.Arts')">Arts</option>
                            <option value="Photography" v-bind:label="$t('gatewayApp.Classification.Photography')">Photography</option>
                            <option value="Biographies" v-bind:label="$t('gatewayApp.Classification.Biographies')">Biographies</option>
                            <option value="BusinessMoney" v-bind:label="$t('gatewayApp.Classification.BusinessMoney')">BusinessMoney</option>
                            <option value="Children" v-bind:label="$t('gatewayApp.Classification.Children')">Children</option>
                            <option value="ComputerTechnology" v-bind:label="$t('gatewayApp.Classification.ComputerTechnology')">ComputerTechnology</option>
                            <option value="History" v-bind:label="$t('gatewayApp.Classification.History')">History</option>
                            <option value="Medical" v-bind:label="$t('gatewayApp.Classification.Medical')">Medical</option>
                            <option value="Travel" v-bind:label="$t('gatewayApp.Classification.Travel')">Travel</option>
                            <option value="Romance" v-bind:label="$t('gatewayApp.Classification.Romance')">Romance</option>
                            <option value="Science" v-bind:label="$t('gatewayApp.Classification.Science')">Science</option>
                            <option value="Math" v-bind:label="$t('gatewayApp.Classification.Math')">Math</option>
                            <option value="SelfHelp" v-bind:label="$t('gatewayApp.Classification.SelfHelp')">SelfHelp</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('gatewayApp.bookBook.bookStatus')" for="book-bookStatus">Book Status</label>
                        <select class="form-control" name="bookStatus" :class="{'valid': !$v.book.bookStatus.$invalid, 'invalid': $v.book.bookStatus.$invalid }" v-model="$v.book.bookStatus.$model" id="book-bookStatus" >
                            <option value="AVAILABLE" v-bind:label="$t('gatewayApp.BookStatus.AVAILABLE')">AVAILABLE</option>
                            <option value="UNAVAILABLE" v-bind:label="$t('gatewayApp.BookStatus.UNAVAILABLE')">UNAVAILABLE</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('gatewayApp.bookBook.location')" for="book-location">Location</label>
                        <select class="form-control" name="location" :class="{'valid': !$v.book.location.$invalid, 'invalid': $v.book.location.$invalid }" v-model="$v.book.location.$model" id="book-location" >
                            <option value="JEONGJA" v-bind:label="$t('gatewayApp.Location.JEONGJA')">JEONGJA</option>
                            <option value="PANGYO" v-bind:label="$t('gatewayApp.Location.PANGYO')">PANGYO</option>
                        </select>
                    </div>
                </div>
                <div>
                    <button type="button" id="cancel-save" class="btn btn-secondary" v-on:click="previousState()">
                        <font-awesome-icon icon="ban"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.cancel')">Cancel</span>
                    </button>
                    <button type="submit" id="save-entity" :disabled="$v.book.$invalid || isSaving" class="btn btn-primary">
                        <font-awesome-icon icon="save"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.save')">Save</span>
                    </button>
                </div>
            </form>
        </div>
    </div>
</template>
<script lang="ts" src="./book-update.component.ts">
</script>

// src/main/webapp/app/entities/book/book/book-update.tsx
import React, { useState, useEffect } from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Row, Col, Label } from 'reactstrap';
import { AvFeedback, AvForm, AvGroup, AvInput, AvField } from 'availity-reactstrap-validation';
import { Translate, translate, ICrudGetAction, ICrudGetAllAction, ICrudPutAction } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { IRootState } from 'app/shared/reducers';

import { getEntity, updateEntity, createEntity, reset } from './book.reducer';
import { IBook } from 'app/shared/model/book/book.model';
import { convertDateTimeFromServer, convertDateTimeToServer, displayDefaultDateTime } from 'app/shared/util/date-utils';
import { mapIdList } from 'app/shared/util/entity-utils';

export interface IBookUpdateProps extends StateProps, DispatchProps, RouteComponentProps<{ id: string }> {}

export const BookUpdate = (props: IBookUpdateProps) => {
  const [isNew, setIsNew] = useState(!props.match.params || !props.match.params.id);

  const { bookEntity, loading, updating } = props;

  const handleClose = () => {
    props.history.push('/book' + props.location.search);
  };

  useEffect(() => {
    if (isNew) {
      props.reset();
    } else {
      props.getEntity(props.match.params.id);
    }
  }, []);

  useEffect(() => {
    if (props.updateSuccess) {
      handleClose();
    }
  }, [props.updateSuccess]);

  const saveEntity = (event, errors, values) => {
    if (errors.length === 0) {
      const entity = {
        ...bookEntity,
        ...values
      };

      if (isNew) {
        props.createEntity(entity);
      } else {
        props.updateEntity(entity);
      }
    }
  };

  return (
    <div>
      <Row className="justify-content-center">
        <Col md="8">
          <h2 id="gatewayApp.bookBook.home.createOrEditLabel">
            <Translate contentKey="gatewayApp.bookBook.home.createOrEditLabel">Create or edit a Book</Translate>
          </h2>
        </Col>
      </Row>
      <Row className="justify-content-center">
        <Col md="8">
          {loading ? (
            <p>Loading...</p>
          ) : (
            <AvForm model={isNew ? {} : bookEntity} onSubmit={saveEntity}>
              {!isNew ? (
                <AvGroup>
                  <Label for="book-id">
                    <Translate contentKey="global.field.id">ID</Translate>
                  </Label>
                  <AvInput id="book-id" type="text" className="form-control" name="id" required readOnly />
                </AvGroup>
              ) : null}
              <AvGroup>
                <Label id="titleLabel" for="book-title">
                  <Translate contentKey="gatewayApp.bookBook.title">Title</Translate>
                </Label>
                <AvField id="book-title" type="text" name="title" />
              </AvGroup>
              <AvGroup>
                <Label id="descriptionLabel" for="book-description">
                  <Translate contentKey="gatewayApp.bookBook.description">Description</Translate>
                </Label>
                <AvField id="book-description" type="text" name="description" />
              </AvGroup>
              <AvGroup>
                <Label id="authorLabel" for="book-author">
                  <Translate contentKey="gatewayApp.bookBook.author">Author</Translate>
                </Label>
                <AvField id="book-author" type="text" name="author" />
              </AvGroup>
              <AvGroup>
                <Label id="publisherLabel" for="book-publisher">
                  <Translate contentKey="gatewayApp.bookBook.publisher">Publisher</Translate>
                </Label>
                <AvField id="book-publisher" type="text" name="publisher" />
              </AvGroup>
              <AvGroup>
                <Label id="isbnLabel" for="book-isbn">
                  <Translate contentKey="gatewayApp.bookBook.isbn">Isbn</Translate>
                </Label>
                <AvField id="book-isbn" type="string" className="form-control" name="isbn" />
              </AvGroup>
              <AvGroup>
                <Label id="publicationDateLabel" for="book-publicationDate">
                  <Translate contentKey="gatewayApp.bookBook.publicationDate">Publication Date</Translate>
                </Label>
                <AvField id="book-publicationDate" type="date" className="form-control" name="publicationDate" />
              </AvGroup>
              <AvGroup>
                <Label id="classificationLabel" for="book-classification">
                  <Translate contentKey="gatewayApp.bookBook.classification">Classification</Translate>
                </Label>
                <AvInput
                  id="book-classification"
                  type="select"
                  className="form-control"
                  name="classification"
                  value={(!isNew && bookEntity.classification) || 'Arts'}
                >
                  <option value="Arts">{translate('gatewayApp.Classification.Arts')}</option>
                  <option value="Photography">{translate('gatewayApp.Classification.Photography')}</option>
                  <option value="Biographies">{translate('gatewayApp.Classification.Biographies')}</option>
                  <option value="BusinessMoney">{translate('gatewayApp.Classification.BusinessMoney')}</option>
                  <option value="Children">{translate('gatewayApp.Classification.Children')}</option>
                  <option value="ComputerTechnology">{translate('gatewayApp.Classification.ComputerTechnology')}</option>
                  <option value="History">{translate('gatewayApp.Classification.History')}</option>
                  <option value="Medical">{translate('gatewayApp.Classification.Medical')}</option>
                  <option value="Travel">{translate('gatewayApp.Classification.Travel')}</option>
                  <option value="Romance">{translate('gatewayApp.Classification.Romance')}</option>
                  <option value="Science">{translate('gatewayApp.Classification.Science')}</option>
                  <option value="Math">{translate('gatewayApp.Classification.Math')}</option>
                  <option value="SelfHelp">{translate('gatewayApp.Classification.SelfHelp')}</option>
                </AvInput>
              </AvGroup>
              <AvGroup>
                <Label id="bookStatusLabel" for="book-bookStatus">
                  <Translate contentKey="gatewayApp.bookBook.bookStatus">Book Status</Translate>
                </Label>
                <AvInput
                  id="book-bookStatus"
                  type="select"
                  className="form-control"
                  name="bookStatus"
                  value={(!isNew && bookEntity.bookStatus) || 'AVAILABLE'}
                >
                  <option value="AVAILABLE">{translate('gatewayApp.BookStatus.AVAILABLE')}</option>
                  <option value="UNAVAILABLE">{translate('gatewayApp.BookStatus.UNAVAILABLE')}</option>
                </AvInput>
              </AvGroup>
              <AvGroup>
                <Label id="locationLabel" for="book-location">
                  <Translate contentKey="gatewayApp.bookBook.location">Location</Translate>
                </Label>
                <AvInput
                  id="book-location"
                  type="select"
                  className="form-control"
                  name="location"
                  value={(!isNew && bookEntity.location) || 'JEONGJA'}
                >
                  <option value="JEONGJA">{translate('gatewayApp.Location.JEONGJA')}</option>
                  <option value="PANGYO">{translate('gatewayApp.Location.PANGYO')}</option>
                </AvInput>
              </AvGroup>
              <Button tag={Link} id="cancel-save" to="/book" replace color="info">
                <FontAwesomeIcon icon="arrow-left" />
                &nbsp;
                <span className="d-none d-md-inline">
                  <Translate contentKey="entity.action.back">Back</Translate>
                </span>
              </Button>
              &nbsp;
              <Button color="primary" id="save-entity" type="submit" disabled={updating}>
                <FontAwesomeIcon icon="save" />
                &nbsp;
                <Translate contentKey="entity.action.save">Save</Translate>
              </Button>
            </AvForm>
          )}
        </Col>
      </Row>
    </div>
  );
};

const mapStateToProps = (storeState: IRootState) => ({
  bookEntity: storeState.book.entity,
  loading: storeState.book.loading,
  updating: storeState.book.updating,
  updateSuccess: storeState.book.updateSuccess
});

const mapDispatchToProps = {
  getEntity,
  updateEntity,
  createEntity,
  reset
};

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(mapStateToProps, mapDispatchToProps)(BookUpdate);
