// src/main/webapp/app/entities/rental/overdue-item/overdue-item.vue
<template>
    <div>
        <h2 id="page-heading">
            <span v-text="$t('gatewayApp.rentalOverdueItem.home.title')" id="overdue-item-heading">Overdue Items</span>
            <router-link :to="{name: 'OverdueItemCreate'}" tag="button" id="jh-create-entity" class="btn btn-primary float-right jh-create-entity create-overdue-item">
                <font-awesome-icon icon="plus"></font-awesome-icon>
                <span  v-text="$t('gatewayApp.rentalOverdueItem.home.createLabel')">
                    Create a new Overdue Item
                </span>
            </router-link>
        </h2>
        <b-alert :show="dismissCountDown"
            dismissible
            :variant="alertType"
            @dismissed="dismissCountDown=0"
            @dismiss-count-down="countDownChanged">
            {{alertMessage}}
        </b-alert>
        <br/>
        <div class="alert alert-warning" v-if="!isFetching && overdueItems && overdueItems.length === 0">
            <span v-text="$t('gatewayApp.rentalOverdueItem.home.notFound')">No overdueItems found</span>
        </div>
        <div class="table-responsive" v-if="overdueItems && overdueItems.length > 0">
            <table class="table table-striped">
                <thead>
                <tr>
                    <th v-on:click="changeOrder('id')"><span v-text="$t('global.field.id')">ID</span> <jhi-sort-indicator :current-order="propOrder" :reverse="reverse" :field-name="'id'"></jhi-sort-indicator></th>
                    <th v-on:click="changeOrder('bookId')"><span v-text="$t('gatewayApp.rentalOverdueItem.bookId')">Book Id</span> <jhi-sort-indicator :current-order="propOrder" :reverse="reverse" :field-name="'bookId'"></jhi-sort-indicator></th>
                    <th v-on:click="changeOrder('dueDate')"><span v-text="$t('gatewayApp.rentalOverdueItem.dueDate')">Due Date</span> <jhi-sort-indicator :current-order="propOrder" :reverse="reverse" :field-name="'dueDate'"></jhi-sort-indicator></th>
                    <th v-on:click="changeOrder('bookTitle')"><span v-text="$t('gatewayApp.rentalOverdueItem.bookTitle')">Book Title</span> <jhi-sort-indicator :current-order="propOrder" :reverse="reverse" :field-name="'bookTitle'"></jhi-sort-indicator></th>
                    <th v-on:click="changeOrder('rentalId')"><span v-text="$t('gatewayApp.rentalOverdueItem.rental')">Rental</span> <jhi-sort-indicator :current-order="propOrder" :reverse="reverse" :field-name="'rentalId'"></jhi-sort-indicator></th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                <tr v-for="overdueItem in overdueItems"
                    :key="overdueItem.id">
                    <td>
                        <router-link :to="{name: 'OverdueItemView', params: {overdueItemId: overdueItem.id}}">{{overdueItem.id}}</router-link>
                    </td>
                    <td>{{overdueItem.bookId}}</td>
                    <td>{{overdueItem.dueDate}}</td>
                    <td>{{overdueItem.bookTitle}}</td>
                    <td>
                        <div v-if="overdueItem.rentalId">
                            <router-link :to="{name: 'RentalView', params: {rentalId: overdueItem.rentalId}}">{{overdueItem.rentalId}}</router-link>
                        </div>
                    </td>
                    <td class="text-right">
                        <div class="btn-group">
                            <router-link :to="{name: 'OverdueItemView', params: {overdueItemId: overdueItem.id}}" tag="button" class="btn btn-info btn-sm details">
                                <font-awesome-icon icon="eye"></font-awesome-icon>
                                <span class="d-none d-md-inline" v-text="$t('entity.action.view')">View</span>
                            </router-link>
                            <router-link :to="{name: 'OverdueItemEdit', params: {overdueItemId: overdueItem.id}}"  tag="button" class="btn btn-primary btn-sm edit">
                                <font-awesome-icon icon="pencil-alt"></font-awesome-icon>
                                <span class="d-none d-md-inline" v-text="$t('entity.action.edit')">Edit</span>
                            </router-link>
                            <b-button v-on:click="prepareRemove(overdueItem)"
                                   variant="danger"
                                   class="btn btn-sm"
                                   v-b-modal.removeEntity>
                                <font-awesome-icon icon="times"></font-awesome-icon>
                                <span class="d-none d-md-inline" v-text="$t('entity.action.delete')">Delete</span>
                            </b-button>
                        </div>
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
        <b-modal ref="removeEntity" id="removeEntity" >
            <span slot="modal-title"><span id="gatewayApp.rentalOverdueItem.delete.question" v-text="$t('entity.delete.title')">Confirm delete operation</span></span>
            <div class="modal-body">
                <p id="jhi-delete-overdueItem-heading" v-text="$t('gatewayApp.rentalOverdueItem.delete.question', {'id': removeId})">Are you sure you want to delete this Overdue Item?</p>
            </div>
            <div slot="modal-footer">
                <button type="button" class="btn btn-secondary" v-text="$t('entity.action.cancel')" v-on:click="closeDialog()">Cancel</button>
                <button type="button" class="btn btn-primary" id="jhi-confirm-delete-overdueItem" v-text="$t('entity.action.delete')" v-on:click="removeOverdueItem()">Delete</button>
            </div>
        </b-modal>
        <div v-show="overdueItems && overdueItems.length > 0">
            <div class="row justify-content-center">
                <jhi-item-count :page="page" :total="queryCount" :itemsPerPage="itemsPerPage"></jhi-item-count>
            </div>
            <div class="row justify-content-center">
                <b-pagination size="md" :total-rows="totalItems" v-model="page" :per-page="itemsPerPage" :change="loadPage(page)"></b-pagination>
            </div>
        </div>
    </div>
</template>

<script lang="ts" src="./overdue-item.component.ts">
</script>

// src/main/webapp/app/entities/rental/overdue-item/overdue-item.tsx
import React, { useState, useEffect } from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Col, Row, Table } from 'reactstrap';
import { Translate, ICrudGetAllAction, TextFormat, getSortState, IPaginationBaseState, JhiPagination, JhiItemCount } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { IRootState } from 'app/shared/reducers';
import { getEntities } from './overdue-item.reducer';
import { IOverdueItem } from 'app/shared/model/rental/overdue-item.model';
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';
import { ITEMS_PER_PAGE } from 'app/shared/util/pagination.constants';

export interface IOverdueItemProps extends StateProps, DispatchProps, RouteComponentProps<{ url: string }> {}

export const OverdueItem = (props: IOverdueItemProps) => {
  const [paginationState, setPaginationState] = useState(getSortState(props.location, ITEMS_PER_PAGE));

  const getAllEntities = () => {
    props.getEntities(paginationState.activePage - 1, paginationState.itemsPerPage, `${paginationState.sort},${paginationState.order}`);
  };

  const sortEntities = () => {
    getAllEntities();
    props.history.push(
      `${props.location.pathname}?page=${paginationState.activePage}&sort=${paginationState.sort},${paginationState.order}`
    );
  };

  useEffect(() => {
    sortEntities();
  }, [paginationState.activePage, paginationState.order, paginationState.sort]);

  const sort = p => () => {
    setPaginationState({
      ...paginationState,
      order: paginationState.order === 'asc' ? 'desc' : 'asc',
      sort: p
    });
  };

  const handlePagination = currentPage =>
    setPaginationState({
      ...paginationState,
      activePage: currentPage
    });

  const { overdueItemList, match, loading, totalItems } = props;
  return (
    <div>
      <h2 id="overdue-item-heading">
        <Translate contentKey="gatewayApp.rentalOverdueItem.home.title">Overdue Items</Translate>
        <Link to={`${match.url}/new`} className="btn btn-primary float-right jh-create-entity" id="jh-create-entity">
          <FontAwesomeIcon icon="plus" />
          &nbsp;
          <Translate contentKey="gatewayApp.rentalOverdueItem.home.createLabel">Create new Overdue Item</Translate>
        </Link>
      </h2>
      <div className="table-responsive">
        {overdueItemList && overdueItemList.length > 0 ? (
          <Table responsive>
            <thead>
              <tr>
                <th className="hand" onClick={sort('id')}>
                  <Translate contentKey="global.field.id">ID</Translate> <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={sort('bookId')}>
                  <Translate contentKey="gatewayApp.rentalOverdueItem.bookId">Book Id</Translate> <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={sort('dueDate')}>
                  <Translate contentKey="gatewayApp.rentalOverdueItem.dueDate">Due Date</Translate> <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={sort('bookTitle')}>
                  <Translate contentKey="gatewayApp.rentalOverdueItem.bookTitle">Book Title</Translate> <FontAwesomeIcon icon="sort" />
                </th>
                <th>
                  <Translate contentKey="gatewayApp.rentalOverdueItem.rental">Rental</Translate> <FontAwesomeIcon icon="sort" />
                </th>
                <th />
              </tr>
            </thead>
            <tbody>
              {overdueItemList.map((overdueItem, i) => (
                <tr key={`entity-${i}`}>
                  <td>
                    <Button tag={Link} to={`${match.url}/${overdueItem.id}`} color="link" size="sm">
                      {overdueItem.id}
                    </Button>
                  </td>
                  <td>{overdueItem.bookId}</td>
                  <td>
                    <TextFormat type="date" value={overdueItem.dueDate} format={APP_LOCAL_DATE_FORMAT} />
                  </td>
                  <td>{overdueItem.bookTitle}</td>
                  <td>{overdueItem.rentalId ? <Link to={`rental/${overdueItem.rentalId}`}>{overdueItem.rentalId}</Link> : ''}</td>
                  <td className="text-right">
                    <div className="btn-group flex-btn-group-container">
                      <Button tag={Link} to={`${match.url}/${overdueItem.id}`} color="info" size="sm">
                        <FontAwesomeIcon icon="eye" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.view">View</Translate>
                        </span>
                      </Button>
                      <Button
                        tag={Link}
                        to={`${match.url}/${overdueItem.id}/edit?page=${paginationState.activePage}&sort=${paginationState.sort},${paginationState.order}`}
                        color="primary"
                        size="sm"
                      >
                        <FontAwesomeIcon icon="pencil-alt" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.edit">Edit</Translate>
                        </span>
                      </Button>
                      <Button
                        tag={Link}
                        to={`${match.url}/${overdueItem.id}/delete?page=${paginationState.activePage}&sort=${paginationState.sort},${paginationState.order}`}
                        color="danger"
                        size="sm"
                      >
                        <FontAwesomeIcon icon="trash" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.delete">Delete</Translate>
                        </span>
                      </Button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </Table>
        ) : (
          !loading && (
            <div className="alert alert-warning">
              <Translate contentKey="gatewayApp.rentalOverdueItem.home.notFound">No Overdue Items found</Translate>
            </div>
          )
        )}
      </div>
      <div className={overdueItemList && overdueItemList.length > 0 ? '' : 'd-none'}>
        <Row className="justify-content-center">
          <JhiItemCount page={paginationState.activePage} total={totalItems} itemsPerPage={paginationState.itemsPerPage} i18nEnabled />
        </Row>
        <Row className="justify-content-center">
          <JhiPagination
            activePage={paginationState.activePage}
            onSelect={handlePagination}
            maxButtons={5}
            itemsPerPage={paginationState.itemsPerPage}
            totalItems={props.totalItems}
          />
        </Row>
      </div>
    </div>
  );
};

const mapStateToProps = ({ overdueItem }: IRootState) => ({
  overdueItemList: overdueItem.entities,
  loading: overdueItem.loading,
  totalItems: overdueItem.totalItems
});

const mapDispatchToProps = {
  getEntities
};

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(mapStateToProps, mapDispatchToProps)(OverdueItem);
