// src/main/webapp/app/entities/book/in-stock-book/in-stock-book-update.tsx
import React, { useState, useEffect } from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Row, Col, Label } from 'reactstrap';
import { AvFeedback, AvForm, AvGroup, AvInput, AvField } from 'availity-reactstrap-validation';
import { Translate, translate, ICrudGetAction, ICrudGetAllAction, ICrudPutAction } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { IRootState } from 'app/shared/reducers';

import { getEntity, updateEntity, createEntity, reset } from './in-stock-book.reducer';
import { IInStockBook } from 'app/shared/model/book/in-stock-book.model';
import { convertDateTimeFromServer, convertDateTimeToServer, displayDefaultDateTime } from 'app/shared/util/date-utils';
import { mapIdList } from 'app/shared/util/entity-utils';

export interface IInStockBookUpdateProps extends StateProps, DispatchProps, RouteComponentProps<{ id: string }> {}

export const InStockBookUpdate = (props: IInStockBookUpdateProps) => {
  const [isNew, setIsNew] = useState(!props.match.params || !props.match.params.id);

  const { inStockBookEntity, loading, updating } = props;

  const handleClose = () => {
    props.history.push('/in-stock-book' + props.location.search);
  };

  useEffect(() => {
    if (isNew) {
      props.reset();
    } else {
      props.getEntity(props.match.params.id);
    }
  }, []);

  useEffect(() => {
    if (props.updateSuccess) {
      handleClose();
    }
  }, [props.updateSuccess]);

  const saveEntity = (event, errors, values) => {
    if (errors.length === 0) {
      const entity = {
        ...inStockBookEntity,
        ...values
      };

      if (isNew) {
        props.createEntity(entity);
      } else {
        props.updateEntity(entity);
      }
    }
  };

  return (
    <div>
      <Row className="justify-content-center">
        <Col md="8">
          <h2 id="gatewayApp.bookInStockBook.home.createOrEditLabel">
            <Translate contentKey="gatewayApp.bookInStockBook.home.createOrEditLabel">Create or edit a InStockBook</Translate>
          </h2>
        </Col>
      </Row>
      <Row className="justify-content-center">
        <Col md="8">
          {loading ? (
            <p>Loading...</p>
          ) : (
            <AvForm model={isNew ? {} : inStockBookEntity} onSubmit={saveEntity}>
              {!isNew ? (
                <AvGroup>
                  <Label for="in-stock-book-id">
                    <Translate contentKey="global.field.id">ID</Translate>
                  </Label>
                  <AvInput id="in-stock-book-id" type="text" className="form-control" name="id" required readOnly />
                </AvGroup>
              ) : null}
              <AvGroup>
                <Label id="titleLabel" for="in-stock-book-title">
                  <Translate contentKey="gatewayApp.bookInStockBook.title">Title</Translate>
                </Label>
                <AvField id="in-stock-book-title" type="text" name="title" />
              </AvGroup>
              <AvGroup>
                <Label id="descriptionLabel" for="in-stock-book-description">
                  <Translate contentKey="gatewayApp.bookInStockBook.description">Description</Translate>
                </Label>
                <AvField id="in-stock-book-description" type="text" name="description" />
              </AvGroup>
              <AvGroup>
                <Label id="authorLabel" for="in-stock-book-author">
                  <Translate contentKey="gatewayApp.bookInStockBook.author">Author</Translate>
                </Label>
                <AvField id="in-stock-book-author" type="text" name="author" />
              </AvGroup>
              <AvGroup>
                <Label id="publisherLabel" for="in-stock-book-publisher">
                  <Translate contentKey="gatewayApp.bookInStockBook.publisher">Publisher</Translate>
                </Label>
                <AvField id="in-stock-book-publisher" type="text" name="publisher" />
              </AvGroup>
              <AvGroup>
                <Label id="isbnLabel" for="in-stock-book-isbn">
                  <Translate contentKey="gatewayApp.bookInStockBook.isbn">Isbn</Translate>
                </Label>
                <AvField id="in-stock-book-isbn" type="string" className="form-control" name="isbn" />
              </AvGroup>
              <AvGroup>
                <Label id="publicationDateLabel" for="in-stock-book-publicationDate">
                  <Translate contentKey="gatewayApp.bookInStockBook.publicationDate">Publication Date</Translate>
                </Label>
                <AvField id="in-stock-book-publicationDate" type="date" className="form-control" name="publicationDate" />
              </AvGroup>
              <AvGroup>
                <Label id="sourceLabel" for="in-stock-book-source">
                  <Translate contentKey="gatewayApp.bookInStockBook.source">Source</Translate>
                </Label>
                <AvInput
                  id="in-stock-book-source"
                  type="select"
                  className="form-control"
                  name="source"
                  value={(!isNew && inStockBookEntity.source) || 'Donated'}
                >
                  <option value="Donated">{translate('gatewayApp.Source.Donated')}</option>
                  <option value="Purchased">{translate('gatewayApp.Source.Purchased')}</option>
                </AvInput>
              </AvGroup>
              <Button tag={Link} id="cancel-save" to="/in-stock-book" replace color="info">
                <FontAwesomeIcon icon="arrow-left" />
                &nbsp;
                <span className="d-none d-md-inline">
                  <Translate contentKey="entity.action.back">Back</Translate>
                </span>
              </Button>
              &nbsp;
              <Button color="primary" id="save-entity" type="submit" disabled={updating}>
                <FontAwesomeIcon icon="save" />
                &nbsp;
                <Translate contentKey="entity.action.save">Save</Translate>
              </Button>
            </AvForm>
          )}
        </Col>
      </Row>
    </div>
  );
};

const mapStateToProps = (storeState: IRootState) => ({
  inStockBookEntity: storeState.inStockBook.entity,
  loading: storeState.inStockBook.loading,
  updating: storeState.inStockBook.updating,
  updateSuccess: storeState.inStockBook.updateSuccess
});

const mapDispatchToProps = {
  getEntity,
  updateEntity,
  createEntity,
  reset
};

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(mapStateToProps, mapDispatchToProps)(InStockBookUpdate);

// src/main/webapp/app/entities/book/in-stock-book/in-stock-book-update.vue
<template>
    <div class="row justify-content-center">
        <div class="col-8">
            <form name="editForm" role="form" novalidate v-on:submit.prevent="save()" >
                <h2 id="gatewayApp.bookInStockBook.home.createOrEditLabel" v-text="$t('gatewayApp.bookInStockBook.home.createOrEditLabel')">Create or edit a InStockBook</h2>
                <div>
                    <div class="form-group" v-if="inStockBook.id">
                        <label for="id" v-text="$t('global.field.id')">ID</label>
                        <input type="text" class="form-control" id="id" name="id"
                               v-model="inStockBook.id" readonly />
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('gatewayApp.bookInStockBook.title')" for="in-stock-book-title">Title</label>
                        <input type="text" class="form-control" name="title" id="in-stock-book-title"
                            :class="{'valid': !$v.inStockBook.title.$invalid, 'invalid': $v.inStockBook.title.$invalid }" v-model="$v.inStockBook.title.$model" />
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('gatewayApp.bookInStockBook.description')" for="in-stock-book-description">Description</label>
                        <input type="text" class="form-control" name="description" id="in-stock-book-description"
                            :class="{'valid': !$v.inStockBook.description.$invalid, 'invalid': $v.inStockBook.description.$invalid }" v-model="$v.inStockBook.description.$model" />
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('gatewayApp.bookInStockBook.author')" for="in-stock-book-author">Author</label>
                        <input type="text" class="form-control" name="author" id="in-stock-book-author"
                            :class="{'valid': !$v.inStockBook.author.$invalid, 'invalid': $v.inStockBook.author.$invalid }" v-model="$v.inStockBook.author.$model" />
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('gatewayApp.bookInStockBook.publisher')" for="in-stock-book-publisher">Publisher</label>
                        <input type="text" class="form-control" name="publisher" id="in-stock-book-publisher"
                            :class="{'valid': !$v.inStockBook.publisher.$invalid, 'invalid': $v.inStockBook.publisher.$invalid }" v-model="$v.inStockBook.publisher.$model" />
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('gatewayApp.bookInStockBook.isbn')" for="in-stock-book-isbn">Isbn</label>
                        <input type="number" class="form-control" name="isbn" id="in-stock-book-isbn"
                            :class="{'valid': !$v.inStockBook.isbn.$invalid, 'invalid': $v.inStockBook.isbn.$invalid }" v-model.number="$v.inStockBook.isbn.$model" />
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('gatewayApp.bookInStockBook.publicationDate')" for="in-stock-book-publicationDate">Publication Date</label>
                        <b-input-group class="mb-3">
                            <b-input-group-prepend>
                                <b-form-datepicker
                                    aria-controls="in-stock-book-publicationDate"
                                    v-model="$v.inStockBook.publicationDate.$model"
                                    name="publicationDate"
                                    class="form-control"
                                    :locale="currentLanguage"
                                    button-only
                                    today-button
                                    reset-button
                                    close-button
                                >
                                </b-form-datepicker>
                            </b-input-group-prepend>
                            <b-form-input id="in-stock-book-publicationDate" type="text" class="form-control" name="publicationDate"  :class="{'valid': !$v.inStockBook.publicationDate.$invalid, 'invalid': $v.inStockBook.publicationDate.$invalid }"
                            v-model="$v.inStockBook.publicationDate.$model"  />
                        </b-input-group>
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('gatewayApp.bookInStockBook.source')" for="in-stock-book-source">Source</label>
                        <select class="form-control" name="source" :class="{'valid': !$v.inStockBook.source.$invalid, 'invalid': $v.inStockBook.source.$invalid }" v-model="$v.inStockBook.source.$model" id="in-stock-book-source" >
                            <option value="Donated" v-bind:label="$t('gatewayApp.Source.Donated')">Donated</option>
                            <option value="Purchased" v-bind:label="$t('gatewayApp.Source.Purchased')">Purchased</option>
                        </select>
                    </div>
                </div>
                <div>
                    <button type="button" id="cancel-save" class="btn btn-secondary" v-on:click="previousState()">
                        <font-awesome-icon icon="ban"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.cancel')">Cancel</span>
                    </button>
                    <button type="submit" id="save-entity" :disabled="$v.inStockBook.$invalid || isSaving" class="btn btn-primary">
                        <font-awesome-icon icon="save"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.save')">Save</span>
                    </button>
                </div>
            </form>
        </div>
    </div>
</template>
<script lang="ts" src="./in-stock-book-update.component.ts">
</script>
