// src/main/webapp/app/entities/book/in-stock-book/in-stock-book.vue
<template>
    <div>
        <h2 id="page-heading">
            <span v-text="$t('gatewayApp.bookInStockBook.home.title')" id="in-stock-book-heading">In Stock Books</span>
            <router-link :to="{name: 'InStockBookCreate'}" tag="button" id="jh-create-entity" class="btn btn-primary float-right jh-create-entity create-in-stock-book">
                <font-awesome-icon icon="plus"></font-awesome-icon>
                <span  v-text="$t('gatewayApp.bookInStockBook.home.createLabel')">
                    Create a new In Stock Book
                </span>
            </router-link>
        </h2>
        <b-alert :show="dismissCountDown"
            dismissible
            :variant="alertType"
            @dismissed="dismissCountDown=0"
            @dismiss-count-down="countDownChanged">
            {{alertMessage}}
        </b-alert>
        <br/>
        <div class="alert alert-warning" v-if="!isFetching && inStockBooks && inStockBooks.length === 0">
            <span v-text="$t('gatewayApp.bookInStockBook.home.notFound')">No inStockBooks found</span>
        </div>
        <div class="table-responsive" v-if="inStockBooks && inStockBooks.length > 0">
            <table class="table table-striped">
                <thead>
                <tr>
                    <th v-on:click="changeOrder('id')"><span v-text="$t('global.field.id')">ID</span> <jhi-sort-indicator :current-order="propOrder" :reverse="reverse" :field-name="'id'"></jhi-sort-indicator></th>
                    <th v-on:click="changeOrder('title')"><span v-text="$t('gatewayApp.bookInStockBook.title')">Title</span> <jhi-sort-indicator :current-order="propOrder" :reverse="reverse" :field-name="'title'"></jhi-sort-indicator></th>
                    <th v-on:click="changeOrder('description')"><span v-text="$t('gatewayApp.bookInStockBook.description')">Description</span> <jhi-sort-indicator :current-order="propOrder" :reverse="reverse" :field-name="'description'"></jhi-sort-indicator></th>
                    <th v-on:click="changeOrder('author')"><span v-text="$t('gatewayApp.bookInStockBook.author')">Author</span> <jhi-sort-indicator :current-order="propOrder" :reverse="reverse" :field-name="'author'"></jhi-sort-indicator></th>
                    <th v-on:click="changeOrder('publisher')"><span v-text="$t('gatewayApp.bookInStockBook.publisher')">Publisher</span> <jhi-sort-indicator :current-order="propOrder" :reverse="reverse" :field-name="'publisher'"></jhi-sort-indicator></th>
                    <th v-on:click="changeOrder('isbn')"><span v-text="$t('gatewayApp.bookInStockBook.isbn')">Isbn</span> <jhi-sort-indicator :current-order="propOrder" :reverse="reverse" :field-name="'isbn'"></jhi-sort-indicator></th>
                    <th v-on:click="changeOrder('publicationDate')"><span v-text="$t('gatewayApp.bookInStockBook.publicationDate')">Publication Date</span> <jhi-sort-indicator :current-order="propOrder" :reverse="reverse" :field-name="'publicationDate'"></jhi-sort-indicator></th>
                    <th v-on:click="changeOrder('source')"><span v-text="$t('gatewayApp.bookInStockBook.source')">Source</span> <jhi-sort-indicator :current-order="propOrder" :reverse="reverse" :field-name="'source'"></jhi-sort-indicator></th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                <tr v-for="inStockBook in inStockBooks"
                    :key="inStockBook.id">
                    <td>
                        <router-link :to="{name: 'InStockBookView', params: {inStockBookId: inStockBook.id}}">{{inStockBook.id}}</router-link>
                    </td>
                    <td>{{inStockBook.title}}</td>
                    <td>{{inStockBook.description}}</td>
                    <td>{{inStockBook.author}}</td>
                    <td>{{inStockBook.publisher}}</td>
                    <td>{{inStockBook.isbn}}</td>
                    <td>{{inStockBook.publicationDate}}</td>
                    <td v-text="$t('gatewayApp.Source.' + inStockBook.source)">{{inStockBook.source}}</td>
                    <td class="text-right">
                        <div class="btn-group">
                            <router-link :to="{name: 'InStockBookView', params: {inStockBookId: inStockBook.id}}" tag="button" class="btn btn-info btn-sm details">
                                <font-awesome-icon icon="eye"></font-awesome-icon>
                                <span class="d-none d-md-inline" v-text="$t('entity.action.view')">View</span>
                            </router-link>
                            <router-link :to="{name: 'InStockBookEdit', params: {inStockBookId: inStockBook.id}}"  tag="button" class="btn btn-primary btn-sm edit">
                                <font-awesome-icon icon="pencil-alt"></font-awesome-icon>
                                <span class="d-none d-md-inline" v-text="$t('entity.action.edit')">Edit</span>
                            </router-link>
                            <b-button v-on:click="prepareRemove(inStockBook)"
                                   variant="danger"
                                   class="btn btn-sm"
                                   v-b-modal.removeEntity>
                                <font-awesome-icon icon="times"></font-awesome-icon>
                                <span class="d-none d-md-inline" v-text="$t('entity.action.delete')">Delete</span>
                            </b-button>
                        </div>
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
        <b-modal ref="removeEntity" id="removeEntity" >
            <span slot="modal-title"><span id="gatewayApp.bookInStockBook.delete.question" v-text="$t('entity.delete.title')">Confirm delete operation</span></span>
            <div class="modal-body">
                <p id="jhi-delete-inStockBook-heading" v-text="$t('gatewayApp.bookInStockBook.delete.question', {'id': removeId})">Are you sure you want to delete this In Stock Book?</p>
            </div>
            <div slot="modal-footer">
                <button type="button" class="btn btn-secondary" v-text="$t('entity.action.cancel')" v-on:click="closeDialog()">Cancel</button>
                <button type="button" class="btn btn-primary" id="jhi-confirm-delete-inStockBook" v-text="$t('entity.action.delete')" v-on:click="removeInStockBook()">Delete</button>
            </div>
        </b-modal>
        <div v-show="inStockBooks && inStockBooks.length > 0">
            <div class="row justify-content-center">
                <jhi-item-count :page="page" :total="queryCount" :itemsPerPage="itemsPerPage"></jhi-item-count>
            </div>
            <div class="row justify-content-center">
                <b-pagination size="md" :total-rows="totalItems" v-model="page" :per-page="itemsPerPage" :change="loadPage(page)"></b-pagination>
            </div>
        </div>
    </div>
</template>

<script lang="ts" src="./in-stock-book.component.ts">
</script>

// src/main/webapp/app/entities/book/in-stock-book/in-stock-book.tsx
import React, { useState, useEffect } from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Col, Row, Table } from 'reactstrap';
import { Translate, ICrudGetAllAction, TextFormat, getSortState, IPaginationBaseState, JhiPagination, JhiItemCount } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { IRootState } from 'app/shared/reducers';
import { getEntities } from './in-stock-book.reducer';
import { IInStockBook } from 'app/shared/model/book/in-stock-book.model';
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';
import { ITEMS_PER_PAGE } from 'app/shared/util/pagination.constants';

export interface IInStockBookProps extends StateProps, DispatchProps, RouteComponentProps<{ url: string }> {}

export const InStockBook = (props: IInStockBookProps) => {
  const [paginationState, setPaginationState] = useState(getSortState(props.location, ITEMS_PER_PAGE));

  const getAllEntities = () => {
    props.getEntities(paginationState.activePage - 1, paginationState.itemsPerPage, `${paginationState.sort},${paginationState.order}`);
  };

  const sortEntities = () => {
    getAllEntities();
    props.history.push(
      `${props.location.pathname}?page=${paginationState.activePage}&sort=${paginationState.sort},${paginationState.order}`
    );
  };

  useEffect(() => {
    sortEntities();
  }, [paginationState.activePage, paginationState.order, paginationState.sort]);

  const sort = p => () => {
    setPaginationState({
      ...paginationState,
      order: paginationState.order === 'asc' ? 'desc' : 'asc',
      sort: p
    });
  };

  const handlePagination = currentPage =>
    setPaginationState({
      ...paginationState,
      activePage: currentPage
    });

  const { inStockBookList, match, loading, totalItems } = props;
  return (
    <div>
      <h2 id="in-stock-book-heading">
        <Translate contentKey="gatewayApp.bookInStockBook.home.title">In Stock Books</Translate>
        <Link to={`${match.url}/new`} className="btn btn-primary float-right jh-create-entity" id="jh-create-entity">
          <FontAwesomeIcon icon="plus" />
          &nbsp;
          <Translate contentKey="gatewayApp.bookInStockBook.home.createLabel">Create new In Stock Book</Translate>
        </Link>
      </h2>
      <div className="table-responsive">
        {inStockBookList && inStockBookList.length > 0 ? (
          <Table responsive>
            <thead>
              <tr>
                <th className="hand" onClick={sort('id')}>
                  <Translate contentKey="global.field.id">ID</Translate> <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={sort('title')}>
                  <Translate contentKey="gatewayApp.bookInStockBook.title">Title</Translate> <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={sort('description')}>
                  <Translate contentKey="gatewayApp.bookInStockBook.description">Description</Translate> <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={sort('author')}>
                  <Translate contentKey="gatewayApp.bookInStockBook.author">Author</Translate> <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={sort('publisher')}>
                  <Translate contentKey="gatewayApp.bookInStockBook.publisher">Publisher</Translate> <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={sort('isbn')}>
                  <Translate contentKey="gatewayApp.bookInStockBook.isbn">Isbn</Translate> <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={sort('publicationDate')}>
                  <Translate contentKey="gatewayApp.bookInStockBook.publicationDate">Publication Date</Translate>{' '}
                  <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={sort('source')}>
                  <Translate contentKey="gatewayApp.bookInStockBook.source">Source</Translate> <FontAwesomeIcon icon="sort" />
                </th>
                <th />
              </tr>
            </thead>
            <tbody>
              {inStockBookList.map((inStockBook, i) => (
                <tr key={`entity-${i}`}>
                  <td>
                    <Button tag={Link} to={`${match.url}/${inStockBook.id}`} color="link" size="sm">
                      {inStockBook.id}
                    </Button>
                  </td>
                  <td>{inStockBook.title}</td>
                  <td>{inStockBook.description}</td>
                  <td>{inStockBook.author}</td>
                  <td>{inStockBook.publisher}</td>
                  <td>{inStockBook.isbn}</td>
                  <td>
                    <TextFormat type="date" value={inStockBook.publicationDate} format={APP_LOCAL_DATE_FORMAT} />
                  </td>
                  <td>
                    <Translate contentKey={`gatewayApp.Source.${inStockBook.source}`} />
                  </td>
                  <td className="text-right">
                    <div className="btn-group flex-btn-group-container">
                      <Button tag={Link} to={`${match.url}/${inStockBook.id}`} color="info" size="sm">
                        <FontAwesomeIcon icon="eye" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.view">View</Translate>
                        </span>
                      </Button>
                      <Button
                        tag={Link}
                        to={`${match.url}/${inStockBook.id}/edit?page=${paginationState.activePage}&sort=${paginationState.sort},${paginationState.order}`}
                        color="primary"
                        size="sm"
                      >
                        <FontAwesomeIcon icon="pencil-alt" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.edit">Edit</Translate>
                        </span>
                      </Button>
                      <Button
                        tag={Link}
                        to={`${match.url}/${inStockBook.id}/delete?page=${paginationState.activePage}&sort=${paginationState.sort},${paginationState.order}`}
                        color="danger"
                        size="sm"
                      >
                        <FontAwesomeIcon icon="trash" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.delete">Delete</Translate>
                        </span>
                      </Button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </Table>
        ) : (
          !loading && (
            <div className="alert alert-warning">
              <Translate contentKey="gatewayApp.bookInStockBook.home.notFound">No In Stock Books found</Translate>
            </div>
          )
        )}
      </div>
      <div className={inStockBookList && inStockBookList.length > 0 ? '' : 'd-none'}>
        <Row className="justify-content-center">
          <JhiItemCount page={paginationState.activePage} total={totalItems} itemsPerPage={paginationState.itemsPerPage} i18nEnabled />
        </Row>
        <Row className="justify-content-center">
          <JhiPagination
            activePage={paginationState.activePage}
            onSelect={handlePagination}
            maxButtons={5}
            itemsPerPage={paginationState.itemsPerPage}
            totalItems={props.totalItems}
          />
        </Row>
      </div>
    </div>
  );
};

const mapStateToProps = ({ inStockBook }: IRootState) => ({
  inStockBookList: inStockBook.entities,
  loading: inStockBook.loading,
  totalItems: inStockBook.totalItems
});

const mapDispatchToProps = {
  getEntities
};

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(mapStateToProps, mapDispatchToProps)(InStockBook);
