// src/main/webapp/app/entities/rental/rental/rental-update.tsx
import React, { useState, useEffect } from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Row, Col, Label } from 'reactstrap';
import { AvFeedback, AvForm, AvGroup, AvInput, AvField } from 'availity-reactstrap-validation';
import { Translate, translate, ICrudGetAction, ICrudGetAllAction, ICrudPutAction } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { IRootState } from 'app/shared/reducers';

import { getEntity, updateEntity, createEntity, reset } from './rental.reducer';
import { IRental } from 'app/shared/model/rental/rental.model';
import { convertDateTimeFromServer, convertDateTimeToServer, displayDefaultDateTime } from 'app/shared/util/date-utils';
import { mapIdList } from 'app/shared/util/entity-utils';

export interface IRentalUpdateProps extends StateProps, DispatchProps, RouteComponentProps<{ id: string }> {}

export const RentalUpdate = (props: IRentalUpdateProps) => {
  const [isNew, setIsNew] = useState(!props.match.params || !props.match.params.id);

  const { rentalEntity, loading, updating } = props;

  const handleClose = () => {
    props.history.push('/rental' + props.location.search);
  };

  useEffect(() => {
    if (isNew) {
      props.reset();
    } else {
      props.getEntity(props.match.params.id);
    }
  }, []);

  useEffect(() => {
    if (props.updateSuccess) {
      handleClose();
    }
  }, [props.updateSuccess]);

  const saveEntity = (event, errors, values) => {
    if (errors.length === 0) {
      const entity = {
        ...rentalEntity,
        ...values
      };

      if (isNew) {
        props.createEntity(entity);
      } else {
        props.updateEntity(entity);
      }
    }
  };

  return (
    <div>
      <Row className="justify-content-center">
        <Col md="8">
          <h2 id="gatewayApp.rentalRental.home.createOrEditLabel">
            <Translate contentKey="gatewayApp.rentalRental.home.createOrEditLabel">Create or edit a Rental</Translate>
          </h2>
        </Col>
      </Row>
      <Row className="justify-content-center">
        <Col md="8">
          {loading ? (
            <p>Loading...</p>
          ) : (
            <AvForm model={isNew ? {} : rentalEntity} onSubmit={saveEntity}>
              {!isNew ? (
                <AvGroup>
                  <Label for="rental-id">
                    <Translate contentKey="global.field.id">ID</Translate>
                  </Label>
                  <AvInput id="rental-id" type="text" className="form-control" name="id" required readOnly />
                </AvGroup>
              ) : null}
              <AvGroup>
                <Label id="userIdLabel" for="rental-userId">
                  <Translate contentKey="gatewayApp.rentalRental.userId">User Id</Translate>
                </Label>
                <AvField id="rental-userId" type="string" className="form-control" name="userId" />
              </AvGroup>
              <AvGroup>
                <Label id="rentalStatusLabel" for="rental-rentalStatus">
                  <Translate contentKey="gatewayApp.rentalRental.rentalStatus">Rental Status</Translate>
                </Label>
                <AvInput
                  id="rental-rentalStatus"
                  type="select"
                  className="form-control"
                  name="rentalStatus"
                  value={(!isNew && rentalEntity.rentalStatus) || 'RENT_AVAILABLE'}
                >
                  <option value="RENT_AVAILABLE">{translate('gatewayApp.RentalStatus.RENT_AVAILABLE')}</option>
                  <option value="RENT_UNAVAILABLE">{translate('gatewayApp.RentalStatus.RENT_UNAVAILABLE')}</option>
                </AvInput>
              </AvGroup>
              <AvGroup>
                <Label id="lateFeeLabel" for="rental-lateFee">
                  <Translate contentKey="gatewayApp.rentalRental.lateFee">Late Fee</Translate>
                </Label>
                <AvField id="rental-lateFee" type="string" className="form-control" name="lateFee" />
              </AvGroup>
              <Button tag={Link} id="cancel-save" to="/rental" replace color="info">
                <FontAwesomeIcon icon="arrow-left" />
                &nbsp;
                <span className="d-none d-md-inline">
                  <Translate contentKey="entity.action.back">Back</Translate>
                </span>
              </Button>
              &nbsp;
              <Button color="primary" id="save-entity" type="submit" disabled={updating}>
                <FontAwesomeIcon icon="save" />
                &nbsp;
                <Translate contentKey="entity.action.save">Save</Translate>
              </Button>
            </AvForm>
          )}
        </Col>
      </Row>
    </div>
  );
};

const mapStateToProps = (storeState: IRootState) => ({
  rentalEntity: storeState.rental.entity,
  loading: storeState.rental.loading,
  updating: storeState.rental.updating,
  updateSuccess: storeState.rental.updateSuccess
});

const mapDispatchToProps = {
  getEntity,
  updateEntity,
  createEntity,
  reset
};

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(mapStateToProps, mapDispatchToProps)(RentalUpdate);

// src/main/webapp/app/entities/rental/rental/rental-update.vue
<template>
    <div class="row justify-content-center">
        <div class="col-8">
            <form name="editForm" role="form" novalidate v-on:submit.prevent="save()" >
                <h2 id="gatewayApp.rentalRental.home.createOrEditLabel" v-text="$t('gatewayApp.rentalRental.home.createOrEditLabel')">Create or edit a Rental</h2>
                <div>
                    <div class="form-group" v-if="rental.id">
                        <label for="id" v-text="$t('global.field.id')">ID</label>
                        <input type="text" class="form-control" id="id" name="id"
                               v-model="rental.id" readonly />
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('gatewayApp.rentalRental.userId')" for="rental-userId">User Id</label>
                        <input type="number" class="form-control" name="userId" id="rental-userId"
                            :class="{'valid': !$v.rental.userId.$invalid, 'invalid': $v.rental.userId.$invalid }" v-model.number="$v.rental.userId.$model" />
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('gatewayApp.rentalRental.rentalStatus')" for="rental-rentalStatus">Rental Status</label>
                        <select class="form-control" name="rentalStatus" :class="{'valid': !$v.rental.rentalStatus.$invalid, 'invalid': $v.rental.rentalStatus.$invalid }" v-model="$v.rental.rentalStatus.$model" id="rental-rentalStatus" >
                            <option value="RENT_AVAILABLE" v-bind:label="$t('gatewayApp.RentalStatus.RENT_AVAILABLE')">RENT_AVAILABLE</option>
                            <option value="RENT_UNAVAILABLE" v-bind:label="$t('gatewayApp.RentalStatus.RENT_UNAVAILABLE')">RENT_UNAVAILABLE</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('gatewayApp.rentalRental.lateFee')" for="rental-lateFee">Late Fee</label>
                        <input type="number" class="form-control" name="lateFee" id="rental-lateFee"
                            :class="{'valid': !$v.rental.lateFee.$invalid, 'invalid': $v.rental.lateFee.$invalid }" v-model.number="$v.rental.lateFee.$model" />
                    </div>
                </div>
                <div>
                    <button type="button" id="cancel-save" class="btn btn-secondary" v-on:click="previousState()">
                        <font-awesome-icon icon="ban"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.cancel')">Cancel</span>
                    </button>
                    <button type="submit" id="save-entity" :disabled="$v.rental.$invalid || isSaving" class="btn btn-primary">
                        <font-awesome-icon icon="save"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.save')">Save</span>
                    </button>
                </div>
            </form>
        </div>
    </div>
</template>
<script lang="ts" src="./rental-update.component.ts">
</script>
