// src/main/webapp/app/entities/rental/returned-item/returned-item.tsx
import React, { useState, useEffect } from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Col, Row, Table } from 'reactstrap';
import { Translate, ICrudGetAllAction, TextFormat, getSortState, IPaginationBaseState, JhiPagination, JhiItemCount } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { IRootState } from 'app/shared/reducers';
import { getEntities } from './returned-item.reducer';
import { IReturnedItem } from 'app/shared/model/rental/returned-item.model';
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';
import { ITEMS_PER_PAGE } from 'app/shared/util/pagination.constants';

export interface IReturnedItemProps extends StateProps, DispatchProps, RouteComponentProps<{ url: string }> {}

export const ReturnedItem = (props: IReturnedItemProps) => {
  const [paginationState, setPaginationState] = useState(getSortState(props.location, ITEMS_PER_PAGE));

  const getAllEntities = () => {
    props.getEntities(paginationState.activePage - 1, paginationState.itemsPerPage, `${paginationState.sort},${paginationState.order}`);
  };

  const sortEntities = () => {
    getAllEntities();
    props.history.push(
      `${props.location.pathname}?page=${paginationState.activePage}&sort=${paginationState.sort},${paginationState.order}`
    );
  };

  useEffect(() => {
    sortEntities();
  }, [paginationState.activePage, paginationState.order, paginationState.sort]);

  const sort = p => () => {
    setPaginationState({
      ...paginationState,
      order: paginationState.order === 'asc' ? 'desc' : 'asc',
      sort: p
    });
  };

  const handlePagination = currentPage =>
    setPaginationState({
      ...paginationState,
      activePage: currentPage
    });

  const { returnedItemList, match, loading, totalItems } = props;
  return (
    <div>
      <h2 id="returned-item-heading">
        <Translate contentKey="gatewayApp.rentalReturnedItem.home.title">Returned Items</Translate>
        <Link to={`${match.url}/new`} className="btn btn-primary float-right jh-create-entity" id="jh-create-entity">
          <FontAwesomeIcon icon="plus" />
          &nbsp;
          <Translate contentKey="gatewayApp.rentalReturnedItem.home.createLabel">Create new Returned Item</Translate>
        </Link>
      </h2>
      <div className="table-responsive">
        {returnedItemList && returnedItemList.length > 0 ? (
          <Table responsive>
            <thead>
              <tr>
                <th className="hand" onClick={sort('id')}>
                  <Translate contentKey="global.field.id">ID</Translate> <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={sort('bookId')}>
                  <Translate contentKey="gatewayApp.rentalReturnedItem.bookId">Book Id</Translate> <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={sort('returnedDate')}>
                  <Translate contentKey="gatewayApp.rentalReturnedItem.returnedDate">Returned Date</Translate>{' '}
                  <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={sort('bookTitle')}>
                  <Translate contentKey="gatewayApp.rentalReturnedItem.bookTitle">Book Title</Translate> <FontAwesomeIcon icon="sort" />
                </th>
                <th>
                  <Translate contentKey="gatewayApp.rentalReturnedItem.rental">Rental</Translate> <FontAwesomeIcon icon="sort" />
                </th>
                <th />
              </tr>
            </thead>
            <tbody>
              {returnedItemList.map((returnedItem, i) => (
                <tr key={`entity-${i}`}>
                  <td>
                    <Button tag={Link} to={`${match.url}/${returnedItem.id}`} color="link" size="sm">
                      {returnedItem.id}
                    </Button>
                  </td>
                  <td>{returnedItem.bookId}</td>
                  <td>
                    <TextFormat type="date" value={returnedItem.returnedDate} format={APP_LOCAL_DATE_FORMAT} />
                  </td>
                  <td>{returnedItem.bookTitle}</td>
                  <td>{returnedItem.rentalId ? <Link to={`rental/${returnedItem.rentalId}`}>{returnedItem.rentalId}</Link> : ''}</td>
                  <td className="text-right">
                    <div className="btn-group flex-btn-group-container">
                      <Button tag={Link} to={`${match.url}/${returnedItem.id}`} color="info" size="sm">
                        <FontAwesomeIcon icon="eye" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.view">View</Translate>
                        </span>
                      </Button>
                      <Button
                        tag={Link}
                        to={`${match.url}/${returnedItem.id}/edit?page=${paginationState.activePage}&sort=${paginationState.sort},${paginationState.order}`}
                        color="primary"
                        size="sm"
                      >
                        <FontAwesomeIcon icon="pencil-alt" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.edit">Edit</Translate>
                        </span>
                      </Button>
                      <Button
                        tag={Link}
                        to={`${match.url}/${returnedItem.id}/delete?page=${paginationState.activePage}&sort=${paginationState.sort},${paginationState.order}`}
                        color="danger"
                        size="sm"
                      >
                        <FontAwesomeIcon icon="trash" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.delete">Delete</Translate>
                        </span>
                      </Button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </Table>
        ) : (
          !loading && (
            <div className="alert alert-warning">
              <Translate contentKey="gatewayApp.rentalReturnedItem.home.notFound">No Returned Items found</Translate>
            </div>
          )
        )}
      </div>
      <div className={returnedItemList && returnedItemList.length > 0 ? '' : 'd-none'}>
        <Row className="justify-content-center">
          <JhiItemCount page={paginationState.activePage} total={totalItems} itemsPerPage={paginationState.itemsPerPage} i18nEnabled />
        </Row>
        <Row className="justify-content-center">
          <JhiPagination
            activePage={paginationState.activePage}
            onSelect={handlePagination}
            maxButtons={5}
            itemsPerPage={paginationState.itemsPerPage}
            totalItems={props.totalItems}
          />
        </Row>
      </div>
    </div>
  );
};

const mapStateToProps = ({ returnedItem }: IRootState) => ({
  returnedItemList: returnedItem.entities,
  loading: returnedItem.loading,
  totalItems: returnedItem.totalItems
});

const mapDispatchToProps = {
  getEntities
};

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(mapStateToProps, mapDispatchToProps)(ReturnedItem);

// src/main/webapp/app/entities/rental/returned-item/returned-item.vue
<template>
    <div>
        <h2 id="page-heading">
            <span v-text="$t('gatewayApp.rentalReturnedItem.home.title')" id="returned-item-heading">Returned Items</span>
            <router-link :to="{name: 'ReturnedItemCreate'}" tag="button" id="jh-create-entity" class="btn btn-primary float-right jh-create-entity create-returned-item">
                <font-awesome-icon icon="plus"></font-awesome-icon>
                <span  v-text="$t('gatewayApp.rentalReturnedItem.home.createLabel')">
                    Create a new Returned Item
                </span>
            </router-link>
        </h2>
        <b-alert :show="dismissCountDown"
            dismissible
            :variant="alertType"
            @dismissed="dismissCountDown=0"
            @dismiss-count-down="countDownChanged">
            {{alertMessage}}
        </b-alert>
        <br/>
        <div class="alert alert-warning" v-if="!isFetching && returnedItems && returnedItems.length === 0">
            <span v-text="$t('gatewayApp.rentalReturnedItem.home.notFound')">No returnedItems found</span>
        </div>
        <div class="table-responsive" v-if="returnedItems && returnedItems.length > 0">
            <table class="table table-striped">
                <thead>
                <tr>
                    <th v-on:click="changeOrder('id')"><span v-text="$t('global.field.id')">ID</span> <jhi-sort-indicator :current-order="propOrder" :reverse="reverse" :field-name="'id'"></jhi-sort-indicator></th>
                    <th v-on:click="changeOrder('bookId')"><span v-text="$t('gatewayApp.rentalReturnedItem.bookId')">Book Id</span> <jhi-sort-indicator :current-order="propOrder" :reverse="reverse" :field-name="'bookId'"></jhi-sort-indicator></th>
                    <th v-on:click="changeOrder('returnedDate')"><span v-text="$t('gatewayApp.rentalReturnedItem.returnedDate')">Returned Date</span> <jhi-sort-indicator :current-order="propOrder" :reverse="reverse" :field-name="'returnedDate'"></jhi-sort-indicator></th>
                    <th v-on:click="changeOrder('bookTitle')"><span v-text="$t('gatewayApp.rentalReturnedItem.bookTitle')">Book Title</span> <jhi-sort-indicator :current-order="propOrder" :reverse="reverse" :field-name="'bookTitle'"></jhi-sort-indicator></th>
                    <th v-on:click="changeOrder('rentalId')"><span v-text="$t('gatewayApp.rentalReturnedItem.rental')">Rental</span> <jhi-sort-indicator :current-order="propOrder" :reverse="reverse" :field-name="'rentalId'"></jhi-sort-indicator></th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                <tr v-for="returnedItem in returnedItems"
                    :key="returnedItem.id">
                    <td>
                        <router-link :to="{name: 'ReturnedItemView', params: {returnedItemId: returnedItem.id}}">{{returnedItem.id}}</router-link>
                    </td>
                    <td>{{returnedItem.bookId}}</td>
                    <td>{{returnedItem.returnedDate}}</td>
                    <td>{{returnedItem.bookTitle}}</td>
                    <td>
                        <div v-if="returnedItem.rentalId">
                            <router-link :to="{name: 'RentalView', params: {rentalId: returnedItem.rentalId}}">{{returnedItem.rentalId}}</router-link>
                        </div>
                    </td>
                    <td class="text-right">
                        <div class="btn-group">
                            <router-link :to="{name: 'ReturnedItemView', params: {returnedItemId: returnedItem.id}}" tag="button" class="btn btn-info btn-sm details">
                                <font-awesome-icon icon="eye"></font-awesome-icon>
                                <span class="d-none d-md-inline" v-text="$t('entity.action.view')">View</span>
                            </router-link>
                            <router-link :to="{name: 'ReturnedItemEdit', params: {returnedItemId: returnedItem.id}}"  tag="button" class="btn btn-primary btn-sm edit">
                                <font-awesome-icon icon="pencil-alt"></font-awesome-icon>
                                <span class="d-none d-md-inline" v-text="$t('entity.action.edit')">Edit</span>
                            </router-link>
                            <b-button v-on:click="prepareRemove(returnedItem)"
                                   variant="danger"
                                   class="btn btn-sm"
                                   v-b-modal.removeEntity>
                                <font-awesome-icon icon="times"></font-awesome-icon>
                                <span class="d-none d-md-inline" v-text="$t('entity.action.delete')">Delete</span>
                            </b-button>
                        </div>
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
        <b-modal ref="removeEntity" id="removeEntity" >
            <span slot="modal-title"><span id="gatewayApp.rentalReturnedItem.delete.question" v-text="$t('entity.delete.title')">Confirm delete operation</span></span>
            <div class="modal-body">
                <p id="jhi-delete-returnedItem-heading" v-text="$t('gatewayApp.rentalReturnedItem.delete.question', {'id': removeId})">Are you sure you want to delete this Returned Item?</p>
            </div>
            <div slot="modal-footer">
                <button type="button" class="btn btn-secondary" v-text="$t('entity.action.cancel')" v-on:click="closeDialog()">Cancel</button>
                <button type="button" class="btn btn-primary" id="jhi-confirm-delete-returnedItem" v-text="$t('entity.action.delete')" v-on:click="removeReturnedItem()">Delete</button>
            </div>
        </b-modal>
        <div v-show="returnedItems && returnedItems.length > 0">
            <div class="row justify-content-center">
                <jhi-item-count :page="page" :total="queryCount" :itemsPerPage="itemsPerPage"></jhi-item-count>
            </div>
            <div class="row justify-content-center">
                <b-pagination size="md" :total-rows="totalItems" v-model="page" :per-page="itemsPerPage" :change="loadPage(page)"></b-pagination>
            </div>
        </div>
    </div>
</template>

<script lang="ts" src="./returned-item.component.ts">
</script>
