// src/main/webapp/app/entities/rental/returned-item/returned-item-update.vue
<template>
    <div class="row justify-content-center">
        <div class="col-8">
            <form name="editForm" role="form" novalidate v-on:submit.prevent="save()" >
                <h2 id="gatewayApp.rentalReturnedItem.home.createOrEditLabel" v-text="$t('gatewayApp.rentalReturnedItem.home.createOrEditLabel')">Create or edit a ReturnedItem</h2>
                <div>
                    <div class="form-group" v-if="returnedItem.id">
                        <label for="id" v-text="$t('global.field.id')">ID</label>
                        <input type="text" class="form-control" id="id" name="id"
                               v-model="returnedItem.id" readonly />
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('gatewayApp.rentalReturnedItem.bookId')" for="returned-item-bookId">Book Id</label>
                        <input type="number" class="form-control" name="bookId" id="returned-item-bookId"
                            :class="{'valid': !$v.returnedItem.bookId.$invalid, 'invalid': $v.returnedItem.bookId.$invalid }" v-model.number="$v.returnedItem.bookId.$model" />
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('gatewayApp.rentalReturnedItem.returnedDate')" for="returned-item-returnedDate">Returned Date</label>
                        <b-input-group class="mb-3">
                            <b-input-group-prepend>
                                <b-form-datepicker
                                    aria-controls="returned-item-returnedDate"
                                    v-model="$v.returnedItem.returnedDate.$model"
                                    name="returnedDate"
                                    class="form-control"
                                    :locale="currentLanguage"
                                    button-only
                                    today-button
                                    reset-button
                                    close-button
                                >
                                </b-form-datepicker>
                            </b-input-group-prepend>
                            <b-form-input id="returned-item-returnedDate" type="text" class="form-control" name="returnedDate"  :class="{'valid': !$v.returnedItem.returnedDate.$invalid, 'invalid': $v.returnedItem.returnedDate.$invalid }"
                            v-model="$v.returnedItem.returnedDate.$model"  />
                        </b-input-group>
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('gatewayApp.rentalReturnedItem.bookTitle')" for="returned-item-bookTitle">Book Title</label>
                        <input type="text" class="form-control" name="bookTitle" id="returned-item-bookTitle"
                            :class="{'valid': !$v.returnedItem.bookTitle.$invalid, 'invalid': $v.returnedItem.bookTitle.$invalid }" v-model="$v.returnedItem.bookTitle.$model" />
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('gatewayApp.rentalReturnedItem.rental')" for="returned-item-rental">Rental</label>
                        <select class="form-control" id="returned-item-rental" name="rental" v-model="returnedItem.rentalId">
                            <option v-bind:value="null"></option>
                            <option v-bind:value="rentalOption.id" v-for="rentalOption in rentals" :key="rentalOption.id">{{rentalOption.id}}</option>
                        </select>
                    </div>
                </div>
                <div>
                    <button type="button" id="cancel-save" class="btn btn-secondary" v-on:click="previousState()">
                        <font-awesome-icon icon="ban"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.cancel')">Cancel</span>
                    </button>
                    <button type="submit" id="save-entity" :disabled="$v.returnedItem.$invalid || isSaving" class="btn btn-primary">
                        <font-awesome-icon icon="save"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.save')">Save</span>
                    </button>
                </div>
            </form>
        </div>
    </div>
</template>
<script lang="ts" src="./returned-item-update.component.ts">
</script>

// src/main/webapp/app/entities/rental/returned-item/returned-item-update.tsx
import React, { useState, useEffect } from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Row, Col, Label } from 'reactstrap';
import { AvFeedback, AvForm, AvGroup, AvInput, AvField } from 'availity-reactstrap-validation';
import { Translate, translate, ICrudGetAction, ICrudGetAllAction, ICrudPutAction } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { IRootState } from 'app/shared/reducers';

import { IRental } from 'app/shared/model/rental/rental.model';
import { getEntities as getRentals } from 'app/entities/rental/rental/rental.reducer';
import { getEntity, updateEntity, createEntity, reset } from './returned-item.reducer';
import { IReturnedItem } from 'app/shared/model/rental/returned-item.model';
import { convertDateTimeFromServer, convertDateTimeToServer, displayDefaultDateTime } from 'app/shared/util/date-utils';
import { mapIdList } from 'app/shared/util/entity-utils';

export interface IReturnedItemUpdateProps extends StateProps, DispatchProps, RouteComponentProps<{ id: string }> {}

export const ReturnedItemUpdate = (props: IReturnedItemUpdateProps) => {
  const [rentalId, setRentalId] = useState('0');
  const [isNew, setIsNew] = useState(!props.match.params || !props.match.params.id);

  const { returnedItemEntity, rentals, loading, updating } = props;

  const handleClose = () => {
    props.history.push('/returned-item' + props.location.search);
  };

  useEffect(() => {
    if (isNew) {
      props.reset();
    } else {
      props.getEntity(props.match.params.id);
    }

    props.getRentals();
  }, []);

  useEffect(() => {
    if (props.updateSuccess) {
      handleClose();
    }
  }, [props.updateSuccess]);

  const saveEntity = (event, errors, values) => {
    if (errors.length === 0) {
      const entity = {
        ...returnedItemEntity,
        ...values
      };

      if (isNew) {
        props.createEntity(entity);
      } else {
        props.updateEntity(entity);
      }
    }
  };

  return (
    <div>
      <Row className="justify-content-center">
        <Col md="8">
          <h2 id="gatewayApp.rentalReturnedItem.home.createOrEditLabel">
            <Translate contentKey="gatewayApp.rentalReturnedItem.home.createOrEditLabel">Create or edit a ReturnedItem</Translate>
          </h2>
        </Col>
      </Row>
      <Row className="justify-content-center">
        <Col md="8">
          {loading ? (
            <p>Loading...</p>
          ) : (
            <AvForm model={isNew ? {} : returnedItemEntity} onSubmit={saveEntity}>
              {!isNew ? (
                <AvGroup>
                  <Label for="returned-item-id">
                    <Translate contentKey="global.field.id">ID</Translate>
                  </Label>
                  <AvInput id="returned-item-id" type="text" className="form-control" name="id" required readOnly />
                </AvGroup>
              ) : null}
              <AvGroup>
                <Label id="bookIdLabel" for="returned-item-bookId">
                  <Translate contentKey="gatewayApp.rentalReturnedItem.bookId">Book Id</Translate>
                </Label>
                <AvField id="returned-item-bookId" type="string" className="form-control" name="bookId" />
              </AvGroup>
              <AvGroup>
                <Label id="returnedDateLabel" for="returned-item-returnedDate">
                  <Translate contentKey="gatewayApp.rentalReturnedItem.returnedDate">Returned Date</Translate>
                </Label>
                <AvField id="returned-item-returnedDate" type="date" className="form-control" name="returnedDate" />
              </AvGroup>
              <AvGroup>
                <Label id="bookTitleLabel" for="returned-item-bookTitle">
                  <Translate contentKey="gatewayApp.rentalReturnedItem.bookTitle">Book Title</Translate>
                </Label>
                <AvField id="returned-item-bookTitle" type="text" name="bookTitle" />
              </AvGroup>
              <AvGroup>
                <Label for="returned-item-rental">
                  <Translate contentKey="gatewayApp.rentalReturnedItem.rental">Rental</Translate>
                </Label>
                <AvInput id="returned-item-rental" type="select" className="form-control" name="rentalId">
                  <option value="" key="0" />
                  {rentals
                    ? rentals.map(otherEntity => (
                        <option value={otherEntity.id} key={otherEntity.id}>
                          {otherEntity.id}
                        </option>
                      ))
                    : null}
                </AvInput>
              </AvGroup>
              <Button tag={Link} id="cancel-save" to="/returned-item" replace color="info">
                <FontAwesomeIcon icon="arrow-left" />
                &nbsp;
                <span className="d-none d-md-inline">
                  <Translate contentKey="entity.action.back">Back</Translate>
                </span>
              </Button>
              &nbsp;
              <Button color="primary" id="save-entity" type="submit" disabled={updating}>
                <FontAwesomeIcon icon="save" />
                &nbsp;
                <Translate contentKey="entity.action.save">Save</Translate>
              </Button>
            </AvForm>
          )}
        </Col>
      </Row>
    </div>
  );
};

const mapStateToProps = (storeState: IRootState) => ({
  rentals: storeState.rental.entities,
  returnedItemEntity: storeState.returnedItem.entity,
  loading: storeState.returnedItem.loading,
  updating: storeState.returnedItem.updating,
  updateSuccess: storeState.returnedItem.updateSuccess
});

const mapDispatchToProps = {
  getRentals,
  getEntity,
  updateEntity,
  createEntity,
  reset
};

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(mapStateToProps, mapDispatchToProps)(ReturnedItemUpdate);
